config/routes.rb
Rails.application.routes.draw do
  resources :basket_items
  resources :baskets
  resources :products
  devise_for :users, controllers: {
                       registrations: "registrations",
                     }
  root "products#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
  has_many :basket_items, dependent: :destroy

  def add_product(product)
    current_item = basket_items.find_by(product_id: product.id)
    if current_item
      current_item.increment(:quantity)
    else
      current_item = basket_items.build(product_id: product.id)
    end
    current_item
  end

  def total_price
    basket_items.to_a.sum { |product| product.total_price }
  end
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :product
  belongs_to :basket

  def total_price
    product.price.to_i * quantity.to_i
  end
end

app/models/concerns/current_basket.rb
module CurrentBasket
  private

  def set_basket
    @basket = Basket.find(session[:basket_id])
  rescue ActiveRecord::RecordNotFound
    @basket = Basket.create
    session[:basket_id] = @basket.id
  end
end

app/models/product.rb
class Product < ApplicationRecord
  before_destroy :not_referenced_by_any_basket_item
  mount_uploader :image, ImageUploader
  belongs_to :user, optional: true
  has_many :basket_items
  validates :name, :description, :price, :release_date, :stock_level, :category, presence: true
  validates :description, length: { maximum: 100 }
  validates :name, length: { maximum: 20 }
  validates :price, numericality: { only_integer: true }, length: { maximum: 5 }

  CATEGORY = %w{ Shoes Tops Shorts Jeans Socks Sweaters Jackets Coats }

  def not_referenced_by_any_basket_item
    unless basket_items.empty?
      errors.add(:base, "Items present")
      throw :abort
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include CurrentBasket
  before_action :set_basket
end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  include CurrentBasket
  before_action :set_basket_item, only: [:show, :edit, :update, :destroy]
  before_action :set_basket, only: [:create]

  def index
    @basket_items = BasketItem.all
  end

  def show
  end

  def new
    @basket_item = BasketItem.new
  end

  def edit
  end

  def create
    product = Product.find(params[:product_id])
    @basket_item = @basket.add_product(product)

    respond_to do |format|
      if @basket_item.save
        format.html { redirect_to @basket_item.basket, notice: "Added to Basket!" }
        format.json { render :show, status: :created, location: @basket_item }
      else
        format.html { render :new }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @basket_item.update(basket_item_params)
        format.html { redirect_to @basket_item, notice: "Basket item was successfully updated." }
        format.json { render :show, status: :ok, location: @basket_item }
      else
        format.html { render :edit }
        format.json { render json: @basket_item.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @basket = Basket.find(session[:basket_id])
    @basket_item.destroy
    respond_to do |format|
      format.html { redirect_to basket_path(@basket), notice: "Item successfully removed." }
      format.json { head :no_content }
    end
  end

  private

  def set_basket_item
    @basket_item = BasketItem.find(params[:id])
  end

  def basket_item_params
    params.require(:basket_item).permit(:product_id)
  end
end

app/controllers/baskets_controller.rb
class BasketsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :invalid_basket
  before_action :set_basket, only: [:show, :edit, :update, :destroy]

  def index
    @baskets = Basket.all
  end

  def show
  end

  def new
    @basket = Basket.new
  end

  def edit
  end

  def create
    @basket = Basket.new(basket_params)

    respond_to do |format|
      if @basket.save
        format.html { redirect_to @basket, notice: "Basket was successfully created." }
        format.json { render :show, status: :created, location: @basket }
      else
        format.html { render :new }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @basket.update(basket_params)
        format.html { redirect_to @basket, notice: "Basket was successfully updated." }
        format.json { render :show, status: :ok, location: @basket }
      else
        format.html { render :edit }
        format.json { render json: @basket.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @basket.destroy if @basket.id == session[:basket_id]
    session[:basket_id] = nil
    respond_to do |format|
      format.html { redirect_to root_path, notice: "Items removed" }
      format.json { head :no_content }
    end
  end

  private

  def set_basket
    @basket = Basket.find(params[:id])
  end

  def basket_params
    params.fetch(:basket, {})
  end

  def invalid_basket
    logger.error "Basket #{params[:id]} invalid"
    redirect_to root_path, notice: "Basket doesn't exist"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @products = Product.all.order("created_at desc")
  end

  def show
  end

  def new
    @product = current_user.products.build
  end

  def edit
  end

  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        ProductMailer.with(product: @product).new_product_email.deliver_later
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :release_date, :price, :image, :category, :stock_level)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def basket_count_visible
    if @basket.basket_items.count > 0
      return "<span>#{@basket.basket_items.count}</span>".html_safe
    end
  end

  def basket_has_products
    return @basket.basket_items.count > 0
  end
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/helpers/baskets_helper.rb
module BasketsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def product_owner(product)
    user_signed_in? && current_user.id == product.user.id
  end
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/views/basket_items/_basket_item.html.erb
<div class="basket-item">
<%= image_tag(basket_item.product.image_url(:thumb)) %><br>
<p>Quantity:<%= basket_item.quantity %></p><br>
<p>Item Name:<%= basket_item.product.name %></p><br>
<p>Item Price: £<%=basket_item.total_price %></p>
<%= button_to 'X', basket_item, method: :delete, data: { confirm: "Are you sure?"}, style: "float: left;" %>
</div>

app/views/basket_items/_form.html.erb
<%= simple_form_for(@basket_item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.association :product %>
    <%= f.association :basket %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/basket_items/edit.html.erb
<h1>Editing Basket Item</h1>

<%= render 'form', basket_item: @basket_item %>

<%= link_to 'Show', @basket_item %> |
<%= link_to 'Back', basket_items_path %>

app/views/basket_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Basket Items</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Basket</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @basket_items.each do |basket_item| %>
      <tr>
        <td><%= basket_item.product_id %></td>
        <td><%= basket_item.basket_id %></td>
        <td><%= link_to 'Show', basket_item %></td>
        <td><%= link_to 'Edit', edit_basket_item_path(basket_item) %></td>
        <td><%= link_to 'Destroy', basket_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket Item', new_basket_item_path %>

app/views/basket_items/new.html.erb
<h1>New Basket Item</h1>

<%= render 'form', basket_item: @basket_item %>

<%= link_to 'Back', basket_items_path %>

app/views/basket_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @basket_item.product_id %>
</p>

<p>
  <strong>Basket:</strong>
  <%= @basket_item.basket_id %>
</p>

<%= link_to 'Edit', edit_basket_item_path(@basket_item) %> |
<%= link_to 'Back', basket_items_path %>

app/views/baskets/_form.html.erb
<%= simple_form_for(@basket) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/baskets/edit.html.erb
<h1>Editing Basket</h1>

<%= render 'form', basket: @basket %>

<%= link_to 'Show', @basket %> |
<%= link_to 'Back', baskets_path %>

app/views/baskets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Baskets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @baskets.each do |basket| %>
      <tr>
        <td><%= link_to 'Show', basket %></td>
        <td><%= link_to 'Edit', edit_basket_path(basket) %></td>
        <td><%= link_to 'Destroy', basket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Basket', new_basket_path %>

app/views/baskets/new.html.erb
<h1>New Basket</h1>

<%= render 'form', basket: @basket %>

<%= link_to 'Back', baskets_path %>

app/views/baskets/show.html.erb
<div>
<%= render(@basket.basket_items) %>
</div>
<div>
<%= button_to 'Continue Shopping', products_path, class: 'basket-buttons' %>
<%= button_to 'Checkout', product_path, class: 'basket-buttons' %>
<%= button_to 'Empty Basket', @basket, method: :delete, data: { confirm: "Are you sure?" }, class: 'basket-buttons' %><br>
</div>
<p>Total: £ <%= @basket.total_price %></p>

app/views/layouts/_header.html.erb
<ul class="nav">
<%= link_to root_path do %>
    <h1 style="padding-left: 15px;">NowSignage</h1>
  <% end  %>
<li class="nav"><a href="/">Home</a></li>
<li class="nav"><a href="/products">Products</a></li>
<li class="nav"><a href="#">Contact</a></li>

<nav>
<% if basket_has_products %>
<%= link_to basket_path(@basket) do %>
<span class="basket-counter">
 Basket
  <%= basket_count_visible %>
  </span><br>
<% end %>
<% end %>
<% if user_signed_in? %>
<% link_to 'Add Product', new_product_path %>
  <%= link_to 'Account', edit_user_registration_path, class:"menu-item" %><br>
    <%= link_to current_user.email, edit_user_registration_path, class:"menu-item" %><br>
    <%= button_to 'Log Out', destroy_user_session_path, :method => "delete", data: { confirm: "Are you sure?" }, class:"menu" %>
<% else %>
<div class="menu-not-logged-in">
<%= link_to "Sign In", new_user_session_path, class:"menu-not-logged-in" %>
<%= link_to "Sign up", new_user_registration_path, class:"menu-not-logged-in" %>
</div>
<% end %>
</nav>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NowSignage</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
    <%= favicon_link_tag asset_path('favicon.ico') %>
  </head>

  <body>
  <% if flash[:notice] %>
    <p class="notice"><%= notice %></p>
  </div>
<% end %>
<% if flash[:alert] %>
  <p class="alert"><%= alert %></p>
</div>
<% end %>

  <%= render "layouts/header" %>
  <div class="container">

    <%= yield %>

  </div>

  </body>
</html>

app/views/products/_form.html.erb
<div class="container">
<%= simple_form_for(@product) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
  <div class="row">
    <div class="col-25">
    <%= f.input :name %>
    </div>
    </div>
    <div class="row">
    <div class="col-75">
    <%= f.input :description %>
    </div>
    </div>
    <div class="row">
    <div class="col-25">
    <%= f.input :price %>
    </div>
    </div>
    <div class="row">
    <div class="col-75">
    <%= f.input :image, as: :file %>
    </div>
    </div>
    <div class="row">
    <div class="col-25">
    <span class="select">
    <%= f.input_field :category, collection: Product::CATEGORY, prompt: "Select category" %>
    </span>
    </div>
    </div>
    <div class="row">
    <div class="col-75">
    <%= f.input :release_date %>
    </div>
    </div>
    <div class="row">
    <div class="col-75">
    <%= f.input :stock_level %>
    </div>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div class="products-list">
<h1 class="title">Products</h1>
<%= link_to '<button class="new-product-btn" type="button">New Product</button>'.html_safe, new_product_path%>
    <% @products.each do |product| %>
      <div class="card">
      <% if product.image %>
      <%= link_to product do %>
      <%= image_tag(product.image_url(:default)) %>
      <% end %>
      <% end %>
        <p><%= product.name %></p>
        <p>£<%= product.price.to_i %></p>
</div>
<% end %>
<div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to '<-Back to Products', products_path %>
<div>
<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<%= image_tag(@product.image_url(:default)) %>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @product.release_date %>
</p>

<p>
  <strong>Price: £</strong>
  <%= @product.price.to_i %>
</p>
<%= link_to 'Edit', edit_product_path(@product) %>
</div>
<%= button_to 'Delete', @product, :method => "delete", data: { confirm: "Are you sure?" }, class: 'product-page-button' %>
<%= button_to 'Add to basket', basket_items_path(product_id: @product), class: 'product-page-button' %>

app/views/store/index.html.erb
<h1>Store#index</h1>
<p>Find me in app/views/store/index.html.erb</p>